### PR TITLE
Fix timetags

### LINKED ISSUE #11: Sending bundles to supercollider - timetag may be incorrect
Hi, I've been using osc-min for formatting OSC messages for quite some time, but never used it for bundles.

Sorry to be a bit vague, but it doesn't seem to work. I'm just checking if you have used bundle sending or know of anyone who has.

```
// this is sending a message
sendosc: {
             "address": "/g_new",
             "args": [
               1000,
               0,
               0
             ]
           }
// supercollider responds
rcvosc : [
             "/n_go",
             1000,
             0,
             -1,
             -1,
             1,
             -1,
             -1
           ]
1000 { parent: 0,
  previous: -1,
  next: -1,
  isGroup: true,
  head: -1,
  tail: -1,
  isPlaying: true,
  isRunning: true }

// this is sending a bundle. this is what is passed to osc.toBuffer
sendosc: {
             "oscType": "bundle",
             "timetag": 1450714988704,
             "elements": [
               {
                 "address": "/g_new",
                 "args": [
                   1001,
                   0,
                   0
                 ]
               }
             ]
           }
```

no response. 

```
        var buf = osc.toBuffer(bundle);
        socket.send(buf, 0, buf.length, this.options.serverPort, this.options.host);
```

I've checked through your code quite a bit. 

It may be something to do with the timetag

    oscTimeTag = exports.toIntegerBuffer timetag, "UInt64"

I think this should be pushed as two Int32 - one is the seconds since epoch, the other is the fractional seconds (picoseconds)

### PR DESCRIPTION
**Pull request by crucialfelix**
Fixes #11 - NTP timetag should be two Int32 …
Previously timetags were encoding JavaScript numbers (which are max 32 bit) as a
64 bit Int which means all time tags were still trapped in the first second of
January 1, 1900.

Now supports:

nil (immediate)
float (seconds from now)
Date (millisecond accurate)
Array `[secondsSince1900, fractionalSeconds]` (0.00000000023283 second accuracy)

Technically this is a breaking change, but I don't think anybody could have used the timestamps before. 
The one thing that is different is that incoming bundles converted with `fromBuffer` will now have an array as the timestamp instead of a number. But the previous number was just the picoseconds anyway.

This also adds some utilities that people can use to convert the timetag to a Date for logging; but it doesn't automatically waste CPU doing that for every incoming bundle.

### CODE REVIEW

**Comment by crucialfelix** [comment]
It is working now in supercollider.js - bundles are being scheduled fine now.

**Comment by russellmcc** [comment]
Thanks so much for doing this work!  After thinking this over, I suppose there was nothing stopping you in the existing version from constructing the timetag yourself as a 64 bit integer, but I agree that it's inconvenient.  Just in case, when I merge this (probably will be a few days because of the holidays), I will bump the major version number.

I love the idea of supporting local-timezone `Date` objects as timetag values for the `toBuffer` call.  This is an awesome change.

I also like the change to return arrays of numbers for `fromBuffer` calls.  This preserves all the accuracy and, along with the utility functions you've written, it's fairly convenient.  I'm not incredibly sold on the utility of the `deltaTimetag` function, since it's unclear to the caller exactly what time is being considered 'now'.  Time passes as the function is called, so functions like this have pretty unclear semantics.

My only serious concern here is about how Javascript numbers should be interpreted as timetags in the `toBuffer` call.  Before, they were interpreted as representing the uint64 of the timetag directly, which I agree is bad.  In your version, they represent relative time.  After thinking it over, I think it might be more clear and useful if numbers represented seconds from epoch directly.  With relative time, it's not clear to the caller at exactly what point Date.now() will be called, so the caller has more control with absolute time.  Does that make sense to you?

**Comment by crucialfelix** [comment]
That was the first thing I thought of  - to pack it myself and try to pass
in a 64 int.
But there is a problem: javascript numbers are all doubles.
So you cannot pass in a number that is 64 int. The highest you can go is 32.

Other things I learned: all JavaScript date objects are time zone aware and
default to your system time.

I exported deltaTimetag which does take an optional explicit "now".
So if you want a relative time with a specific now:  osc.deltaTimetag(secs,
now)
Maybe its the documentation that is unclear. now is optional.

If you need higher precision (for granular synthesis) then you can assemble
the full pair.

> My only serious concern here is about how Javascript numbers should be
interpreted as timetags in the toBuffer call.

Yep, I know this is the one actual breaking change. Worth thinking through
it carefully.

> After thinking it over, I think it might be more clear and useful if
numbers represented seconds from epoch directly.

Then it has to be unix epoch so essentially its the same as date.getTime()
[though that is milliseconds since unix epoch]
My thinking is that you can already pass in a Date, so there is no extra
value in being able to pass in a unix timestamp.

SuperCollider lang only allows sending bundles with floats indicating
relative time.
The default is 0 : asap.

If that is interpreted as seconds since epoch then t is jan 1 1900.

Most usage of sending a bundle is to send it right away or possibly with a
bit of latency so it comes out smooth on the other end.
If sclang took proper Dates (was we have here now in osc-min) then you
could schedule events reliably and scsynth would play them
in a steady fashion. if you have CPU drag in sclang or in your javascript
browser app and you are using all relative-to-now numbers
then time is going to get dragged down.

So for any serious sequencing, don't use deltaTimetag, use a scheduling
class and have it output Dates

In the end as long as there are nice utility funcs for constructing that
time tag, then any of us that use the lib will be happy.

**Comment by crucialfelix** [comment]
On further thought, this would be really great to just pass a float:

seconds since unix (1970) with many digits of subseconds (not just milliseconds) and that gets converted to NTP tag

Then for a sequencer you only need to save the time that you hit play and then you can easily calculate precise floating point numbers for each event:  eventBeat * (1/beatsPerSecond) + startTimestamp

I wouldn't want to go through a Date class at all.

**Comment by russellmcc** [comment]
Awesome.  Just to make sure I understand, you're proposing to change `toBuffer` to accept either a number which represents seconds from UNIX epoch, OR an array of two numbers that represent the two uint32 fields from the osc time tag?

And `fromBuffer` will provide an array of two uint32 fields?

This makes perfect sense to me.  Along with some convenience functions, this will be quite easy to use.  Let me know if you want me to make the modifications to your pull request to achieve this - I'd be happy to if you don't have the time.

**Comment by crucialfelix** [comment]
Yes, I now agree with you that a number should be seconds from unix epoch (including the fractional seconds)

toBuffer would also still accept a Date if you gave it one.

I'll make the change then I'll work with it for a bit using supercollider.js just to see if I run into any other issues. We should be able to merge it in a few days.

**Comment by crucialfelix** [comment]
OK, I've been using it successfully and the API is easy to use. I think you could merge and release it now.

File: lib/index.js [hunk 1]
```diff
@@ -166,4 +178,31 @@
...
+
+//~api~
+//----
+//### .timetagToDate(ntpTimeTag)
+// Convert a timetag array to a JavaScript Date object in your local timezone.
+//
+// Received OSC bundles converted with `fromBuffer` will have a timetag array:
+// [secondsSince1970, fractionalSeconds]
+// This utility is useful for logging. Accuracy is reduced to milliseconds,
+// but the returned Date object also has `fractionalSecondsInt` and `fractionalSecondsFloat` set if you need full accuracy (0.00000000023283 second, or 2^32 per second)
```
Comment (russellmcc) [inline lib/index.js]: There are serious performance implications to glomming extra fields onto existing structures in at least V8: (http://ariya.ofilabs.com/2012/02/javascript-object-structure-speed-matters.html).  I wouldn't add these fields, as they are already available in the timetag.

File: lib/osc-utilities.coffee [hunk 2]
```diff
@@ -129,6 +129,98 @@ exports.splitInteger = (buffer, type) ->
...
+  dd.setUTCFullYear(date.getUTCFullYear())
+  dd.setUTCMonth(date.getUTCMonth())
+  dd.setUTCDate(date.getUTCDate())
+  dd.setUTCHours(date.getUTCHours())
+  dd.setUTCMinutes(date.getUTCMinutes())
+  dd.setUTCSeconds(date.getUTCSeconds())
+  dd.setUTCMilliseconds(fracs * 1000)
+  # set fractional seconds with full precision
+  # to date object
+  dd.fractionalSecondsInt = fractional
```
Comment (russellmcc) [inline lib/osc-utilities.coffee]: As I mentioned above, this is not necessary and can seriously hurt performance of client code in at least V8

File: lib/osc-utilities.coffee [hunk 3]
```diff
@@ -129,6 +129,98 @@ exports.splitInteger = (buffer, type) ->
...
+  dd.fractionalSecondsFloat = fracs
+  return dd
+
+# Make NTP timestamp array for relative future: now + seconds
+# Accuracy of 'now' limited to milliseconds but 'seconds' may be a full 32 bit float
+exports.deltaTimetag = (seconds, now) ->
```
Comment (russellmcc) [inline lib/osc-utilities.coffee]: I think this function is now unnecessary - clients who need it can implement it trivially

File: lib/index.js [hunk 4]
```diff
@@ -84,12 +84,24 @@
 //               elements : [element1, element]
 //           }
 //
-//   Where the timetag is a javascript-native numeric value of the timetag,
-//   and elements is an array of either an _OSC Bundle_ or an _OSC Message_
-//   The `oscType` field is optional, but is always returned by api functions.
+//   `oscType` ("bundle"|"message")
```
Comment (russellmcc) [inline lib/index.js]: I don't think this is right - osc bundles have to be bundle.  I would remove this line.

**Comment by russellmcc** [comment]
Looks great modulo inline comments I just made above.  Also, please land this on a non-master branch so I can bump the version number before merging to master.

Thanks for doing all this work!  I think this is going to make a big improvement.

**Comment by russellmcc** [comment]
I'm happy to do the updates I requested above post-merge if you agree with them.

File: lib/index.js (hunk 1 above)
Comment (crucialfelix) [inline lib/index.js]: this is true. I was mentioning that performance issue to a friend the other day and then thought "wait, I just did that in osc-min".  I'll drop those

File: lib/osc-utilities.coffee (hunk 2 above)
Comment (crucialfelix) [inline lib/osc-utilities.coffee]: you mean line 194, fractionalSecondsInt ?

File: lib/osc-utilities.coffee (hunk 3 above)
Comment (crucialfelix) [inline lib/osc-utilities.coffee]: which function ? github isn't making it clear to me which line you are referring to. I find each of those functions useful. especially timetagToDate which is used in logging when I receive an incoming osc bundle.

**Comment by crucialfelix** [comment]
Done ! I think you should merge it yourself. You can do that with hub by checking it locally and then merging to a release or dev branch as you like:

git checkout https://github.com/russellmcc/node-osc-min/pull/12

https://hub.github.com/
